openapi: 3.0.0
info:
  version: 1.0.1
  title: Newsletter subscribe API
components:
  securitySchemes:
    ShopperToken:
      type: http
      scheme: bearer
      flows:
        authorizationCode:
          authorizationUrl: https://kv7kzm78.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/f_ecom_zzap_249/oauth2/authorize
          tokenUrl: https://kv7kzm78.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/f_ecom_zzap_249/oauth2/token
          scopes:
            c_newsletter_r: Newsletter subscribe
paths:
  /subscribe:
    post:
      summary: Update Newsletter information
      operationId: setNewsletterInfo
      parameters:
        - in: query
          name: c_email
          required: true
          schema:
            type: string
        - in: query
          name: c_firstName
          required: true
          schema:
            type: string
        - in: query
          name: c_lastName
          required: true
          schema:
            type: string
        - in: query
          name: c_phone
          required: true
          schema:
            type: string
        - in: query
          name: c_consent
          required: true
          schema:
            type: boolean
        - in: query
          name: siteId
          required: true
          schema:
            type: string
            minLength: 1
        - in: query
          name: locale
          required: false
          schema:
            type: string
            minLength: 1
      responses:
        "200":
          description: Update newsletter information
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        "404":
          description: Shows that the customer is not found
          content:
            application/json:
              examples:
                not_found:
                  value:
                    {
                      "type": "https://api.commercecloud.salesforce.com/documentation/error/v1/custom-errors/customer-not-found",
                    }
security:
  - ShopperToken: ["c_newsletter_r"]